-- Baseline schema, mirroring the DDL Hibernate generated before Flyway was introduced.

create table products (
    id uuid not null,
    name varchar(255) not null,
    price numeric(19,2) not null,
    active boolean not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint products_pkey primary key (id)
);

create table inventories (
    id uuid not null,
    product_id uuid not null,
    available integer not null,
    reserved integer not null,
    version bigint,
    constraint inventories_pkey primary key (id),
    constraint uk_inventory_product_id unique (product_id),
    constraint fk_inventories_product foreign key (product_id) references products (id)
);

create table orders (
    id uuid not null,
    customer_email varchar(255),
    status varchar(255),
    created_at timestamp(6) with time zone,
    constraint orders_pkey primary key (id),
    constraint orders_status_check check (status in ('CREATED', 'PAID', 'CANCELLED'))
);

create table order_items (
    id bigint generated by default as identity,
    order_id uuid not null,
    product_id uuid not null,
    product_name_snapshot varchar(255) not null,
    unit_price_at_purchase numeric(19,2) not null,
    quantity integer not null,
    constraint order_items_pkey primary key (id),
    constraint fk_order_items_order foreign key (order_id) references orders (id)
);

create table outbox_events (
    id uuid not null,
    aggregate_type varchar(255) not null,
    aggregate_id uuid not null,
    type varchar(255) not null,
    payload_json oid not null,
    occurred_at timestamp(6) with time zone not null,
    created_at timestamp(6) with time zone not null,
    published_at timestamp(6) with time zone,
    constraint outbox_events_pkey primary key (id)
);

create index idx_outbox_published_at on outbox_events (published_at);
create index idx_outbox_occurred_at on outbox_events (occurred_at);
